Задачки с кодэварэс
ISUCT/TProgramming_2023 pull request #2
Opened 2023-09-26 11:29 UTC by spleekz

2023-09-27 05:18 UTC, jskonst commented
Не хватает еще задачек :(

2023-09-27 05:20 UTC, jskonst commented on codewars/Build Tower/tower.js
> +			[] ,
важно помнить что редьюсер медленее чем map или foreach

2023-09-27 05:21 UTC, jskonst commented on codewars/Convert string to camel case/case.js
> +function capitalize( str ) {
усложнено решение, можно было сильно проще

2023-09-27 05:22 UTC, jskonst commented on codewars/Simple Pig Latin/pig_latin.js
> +	return str.replace( /(\w)(\w+)/g , '$2$1ay' );
:+1:

2023-11-18 16:19 UTC, jskonst requested changes

2023-11-18 16:19 UTC, jskonst commented on rpgsaga/saga/src/index.ts
> -import { Phone } from './phone';
index то можно оставить - для примера (только вызывать свои экземпляры)

2023-11-18 16:19 UTC, jskonst commented on rpgsaga/saga/src/phone.ts
> +	year : number;
приватные

2023-11-18 16:19 UTC, jskonst commented on rpgsaga/saga/src/phone.ts
> +	};
toString добавьте

2023-11-18 16:19 UTC, jskonst commented on rpgsaga/saga/src/phone.ts
> +		this.year = year;
используйте set для присвоения значений, кроме того при не правильных параметрах бросайте exception

2023-11-18 16:19 UTC, jskonst commented on rpgsaga/saga/src/phone.ts
> +		) {
вот это надо проверять при попытке установить значения

2023-11-19 15:07 UTC, artembunichev commented on rpgsaga/saga/src/phone.ts
> +	year : number;
а почему модель и год производства должны быть приватными?

2024-01-13 15:38 UTC, closed without merging